apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: prod-
namespace: prod
images:
  - name: ghcr.io/code-and-secure/autonomous-release-platform
    newTag: sha-901bc54
replicas:
  - name: autonomous-release-app
    count: 3
