apiVersion: v1
kind: Service
metadata:
  name: autonomous-release-service
spec:
  selector:
    app: autonomous-release-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
