apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: dev-
namespace: dev
images:
  - name: ghcr.io/example-org/autonomous-release-platform
    newTag: latest
replicas:
  - name: autonomous-release-app
    count: 1
